import { USE_HEYGEN } from './config.js';
const els={start:btnStart,send:btnSend,input:textInput,status:status,videoWrapper:videoWrapper,videoFrame:videoFrame,btnUnmute:btnUnmute,btnCloseVideo:btnCloseVideo,mic:btnMic,avatar:avatarStub,container:avatarContainer};
function speak(t){try{if('speechSynthesis'in window){const u=new SpeechSynthesisUtterance(t);speechSynthesis.cancel();speechSynthesis.speak(u);}}catch{}}
function say(t,v=true){els.status.textContent=t;if(v)speak(t)}
const STATE={IDLE:'idle',CHOICE:'choice',ASK_VIDEO:'ask_video',PLAYING:'playing'};const ctx={session:false,state:STATE.IDLE,idle:null,rec:null,recOn:false,lowered:false,pending:null};
function idle(){clearTimeout(ctx.idle);ctx.idle=setTimeout(()=>say('Still there? (yes/no)',false),30000)}
function lower(b){if(b&&!ctx.lowered){els.avatar.classList.add('lowered');ctx.lowered=true}else if(!b&&ctx.lowered){els.avatar.classList.remove('lowered');ctx.lowered=false}}
function startSession(){ctx.session=true;ctx.state=STATE.CHOICE;idle();say('Hi! Choose Module 1, Module 2, or say both.')}
function handleChoice(t){if(/explain both|both modules|both/i.test(t)){ctx.pending='1';ctx.state=STATE.ASK_VIDEO;say('Module 1: play a quick video? (yes/no)');return}
if(/module\s*1|finance/i.test(t)){ctx.pending='1';ctx.state=STATE.ASK_VIDEO;say('Module 1: play a quick video? (yes/no)');return}
if(/module\s*2|procurement|payables/i.test(t)){ctx.pending='2';ctx.state=STATE.ASK_VIDEO;say('Module 2: play a quick video? (yes/no)');return}}
function handleVideoConfirm(t){if(/\b(yes|y)\b/i.test(t)){showVideo(ctx.pending==='1'?'dQw4w9WgXcQ':'tgbNymZ7vqY');say('Playing.',false);return}
if(/\b(no|n)\b/i.test(t)){ctx.state=STATE.CHOICE;say('Okay, skipping. Choose Module 1, Module 2, or both.',false);return}}
function showVideo(id){ctx.state=STATE.PLAYING;lower(true);els.videoWrapper.classList.remove('hidden');els.videoFrame.innerHTML=`<iframe id="ytFrame" src="https://www.youtube.com/embed/${id}?autoplay=1&mute=1&playsinline=1" allow="autoplay; encrypted-media" allowfullscreen></iframe>`}
function closeVideo(){els.videoFrame.innerHTML='';els.videoWrapper.classList.add('hidden');lower(false);ctx.state=STATE.CHOICE;say('Video closed. Choose Module 1, Module 2, or both.',false)}
function maybeBG(t){let img='./public/default-image.jpg';if(/harvard/i.test(t))img='./public/harvard-university-title.jpg';else if(/oxford/i.test(t))img='./public/oxford-university-title.jpg';else if(/stanford/i.test(t))img='./public/stanford-university-title.jpg';els.container.style.background=`#000 url('${img}') center/cover no-repeat`}
function handleInput(r){const t=(r||'').trim();if(!t)return;idle();maybeBG(t);if(!ctx.session){if(/\bhello\b|\bhi\b|\bhey\b/i.test(t))startSession();else say('Say "hello" to begin.',false);return}
if(ctx.state===STATE.CHOICE)return handleChoice(t);if(ctx.state===STATE.ASK_VIDEO)return handleVideoConfirm(t);if(ctx.state===STATE.PLAYING&&/close|stop video/i.test(t))return closeVideo()}
function initRec(){const C=window.SpeechRecognition||window.webkitSpeechRecognition;if(!C)return null;const r=new C();r.lang='en-US';r.continuous=false;r.interimResults=false;r.onresult=e=>{const tx=e.results[0][0].transcript;els.input.value=tx;handleInput(tx)};r.onend=()=>{if(ctx.recOn)tryStartRec()};r.onerror=()=>{ctx.recOn=false;els.mic.textContent='Mic: Off'};return r}
function tryStartRec(){try{ctx.rec&&ctx.rec.start()}catch{}}
function toggleMic(){if(!ctx.rec)ctx.rec=initRec();if(!ctx.rec)return alert('Mic not supported in this browser. Try Chrome.');ctx.recOn=!ctx.recOn;els.mic.textContent=ctx.recOn?'Mic: On':'Mic: Off';if(ctx.recOn)tryStartRec()}
els.start.addEventListener('click',()=>startSession());els.send.addEventListener('click',()=>{handleInput(els.input.value);els.input.value=''});els.input.addEventListener('keydown',e=>{if(e.key==='Enter'){handleInput(els.input.value);els.input.value=''}});els.btnUnmute.addEventListener('click',()=>{const f=document.getElementById('ytFrame');if(f)f.src=f.src.replace('mute=1','mute=0')});els.btnCloseVideo.addEventListener('click',()=>closeVideo());els.mic.addEventListener('click',()=>toggleMic());console.log('Drivestream Avatar Demo loaded. USE_HEYGEN=',USE_HEYGEN);